### ISSUE TITLE
Can you help me with this issue?

### ISSUE THREAD

**Issue by trsh** [fegennari/3DWorld#14] opened 2022-03-26 18:17 UTC
I downloaded the project and exe from release. When I run exe I got this error:
```
C:\Users\janis>C:\Users\janis\Downloads\3DWorld-master\3DWorld-master\3DWorld.exe
Starting 3DWorld
*** Error: Could not open input configuration file file 'scene_config/config_pre.txt'.
*** Error: Could not open input configuration file file 'scene_config/config_post.txt'.
Loading.....alut error: There was an error opening the ALC device
alutInit failed
```

**Comment by fegennari** [comment] 2022-03-26 19:04
You have to clone the entire git repo, and then place the release executable in the root of the git project. The scene_config directory and required DLLs are there, along with all of the other required assets. This data is too large to package with every release.

**Comment by fegennari** [comment] 2022-05-24 04:23
It's been awhile. Did you ever solve this? I just updated the alut project files to toolset v143 and added both the win32 and x64 libraries to the git repo. I'm going to close this issue since I never heard back from you and can't reproduce the problem. Feel free to re-open it if needed, with some more info.

**Closed by fegennari** 2022-05-24 04:23 UTC

**Comment by trsh** [comment] 2022-05-24 05:59
Sorry I did lost interest in this project. I good, but not the thing I was looking for.
