### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [fegennari/3DWorld#5] opened 2020-03-19 16:06 UTC
I would like to point out that identifiers like “[`_ASTEROID_H_`](https://github.com/fegennari/3DWorld/blob/0323c8fbb121e9088170d5bc5e1858deb7af52d6/src/asteroid.h#L5 "Update candidate")” and “[`_BUILDING_H_`](https://github.com/fegennari/3DWorld/blob/79204f5adf6069756f0e4eab15395e358aef8c0d/src/buildings.h#L5 "Another update candidate")” [do not fit](https://www.securecoding.cert.org/confluence/display/c/DCL37-C.+Do+not+declare+or+define+a+reserved+identifier#DCL37-C.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28IncludeGuard%29 "Do not use identifiers which are reserved for the compiler implementation.") to the expected naming convention of the C language standard.
Would you like to adjust your selection for unique names?

**Comment by fegennari** [comment] 2020-03-20 08:04
Thanks. I wasn't aware of the underscore naming convention rules. I've never run into a problem with this before. It's probably best to change all 66 headers to use "#pragma once" instead of these macro include guards to match the newer headers that already do it this way. That took a while but it's committed.

**Closed by fegennari** 2020-03-20 08:04 UTC

**Comment by elfring** [comment] 2020-03-20 08:14
[The construct “`#pragma once`” is not standard compliant](https://stackoverflow.com/questions/23696115/is-pragma-once-part-of-the-c11-standard/23699893#answer-23699893 "Is #pragma once part of the C++11 standard?").

**Comment by fegennari** [comment] 2020-03-20 08:24
Interesting. I wasn't aware of that either. I have been using this in both Visual Studio and gcc for a while now without problems. I've had "#pragma once" in 3DWorld for about two years now in some of the newer header files. While it may not be standard compliant, I prefer to leave it in until I run into an actual problem. Also, because it's been in use in other files, I don't consider this change a regression. Maybe I'll get back to this later. Thank you.
