### ISSUE TITLE
Not detecting OpenGL 4.5

### ISSUE THREAD

**Issue by Wongani-Ngoma** [fegennari/3DWorld#24] opened 2024-09-25 09:11 UTC
In `init_glew()`, it checks if OpenGL 4.5 is supported, and on my machine, which supports has the latest graphics driver for my GPU and supports all OpenGL versions till 4.6, it fails, assuming that 4.5 is not supported. I changed the method parameter to GL_VERSION_4_6, and it worked, GL_VERSION_4_4 also worked, but I still don't know why 4.5 is not detected.
I am new to graphics, so I don't know if this is really an issue or if it's me that's missing something.

**Comment by fegennari** [comment] 2024-09-25 18:05
It sounds like a GLEW bug. GLEW is pretty old and I don't think there's a newer release to try. OpenGL 4.5 is the correct version for 3DWorld. 4.4 is missing features and I'm not using any 4.6 features. Maybe a hacky fix is to check for GL_VERSION_4_6 if the GL_VERSION_4_5 check fails. I can't reproduce the problem, so I can't properly test the fix. Maybe you can test it once the fix is committed.

**Comment by fegennari** [comment] 2024-09-26 05:43
I looked at the GLEW source code and the logic seems like it would always return true for GL_VERSION_4_5 if GL_VERSION_4_6 was supported, so I don't understand how this can fail.

One thing you can try is to use a core context. Are you using the default config file, mapx/config_mapx.txt? If so, open the file mapx/config_mapx_base.txt and change line 25 from:
use_core_context 0
to:
use_core_context 1
and see if that fixes it.

Another experiment is to comment out the exit(1); on line 29 of gl_ext_arb.cpp so that 3DWorld doesn't exit. Does this work, or do you get a different error? This will tell us if the problem is just with the glewIsSupported() call or if it really doesn't support OpenGL 4.5.

**Comment by fegennari** [comment] 2024-09-28 00:26
I think I've fixed it now. I'm going to close this issue. Re-open if it you still have problems. Thanks.

**Closed by fegennari** 2024-09-28 00:26 UTC
